name: Lint
on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: install dependencies
      run: npm install
    
    - name: lint
      run: npm run lint